<a href="https://colab.research.google.com/github/codebiney/torch-tutorial/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np

In [7]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [8]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [11]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [12]:
tensor_b * tensor_a

tensor([ 5, 12, 21, 32])

In [13]:
torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [14]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [18]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [19]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])